# Generated by Django 4.2.1 on 2023-05-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
